./build_version.sh 3 6 15 python-3.6 "LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/python3.? /tests/basic.py"
./build_version.sh 3 7 15 python-3.7 "LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/python3.? /tests/basic.py"
./build_version.sh 3 8 15 python-3.8-embed "LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/python3.? /tests/basic.py"
./build_version.sh 3 9 15 python-3.9-embed "LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/python3.? /tests/basic.py"
./build_version.sh 3 10 8 python-3.10-embed "LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/python3.1? /tests/basic.py"
./build_version.sh 3 11 0 python-3.11-embed "LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/python3.1? /tests/basic.py"
